server:
  port: 8083
spring:
  application:
    name: user-service
  data:
    mongodb:
      database: watches_db
      port: 27017
      host: localhost
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB